apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecowtestplatform
  labels:
    app: wisecowtestplatform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wisecowtestplatform
  template:
    metadata:
      labels:
        app: wisecowtestplatform
    spec:
      containers:
      - name: wisecowtestplatform
        image: spicycriminal43/testing-wisecow
        ports:
        - containerPort: 4499
