apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecowtest
  labels:
    app: wisecowtest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wisecowtest
  template:
    metadata:
      labels:
        app: wisecowtest
    spec:
      containers:
      - name: wisecowtest
        image: spicycriminal43/wisecowtest:latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 4499
