apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wisecowtest
spec:
  ingressClassName: wisecowtest
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wisecowtest
            port:
              number: 4499
